### PR TITLE
Allow overriding cloudName used in tests

### PR DESCRIPTION
**Pull request by mortenlj**
This allows for using other cloud providers in cases where GCP has problems, like the case was today.

### CODE REVIEW

**Comment by byashimov** [comment]
Hi @mortenlj!
Obviously, this is must have. Thanks for the contribution. 
Currently there are might be some issues on GCP side. I'll try to run tests tomorrow.

**Comment by byashimov** [comment]
Hey!
Could you please do few things?

1. rename `testCloudName` to `testPrimaryCloudName`
2. add `testSecondaryCloudName`, set it to `google-europe-west2`, and use if for [this](https://github.com/aiven/aiven-operator/blob/main/tests/projectvpc_test.go#L42)

Thanks.

**Comment by mortenlj** [comment]
Resolved the conflicts and took a stab at fixing the other thing, but the tests consistently time out so not really sure it worked as expected ... Would be good if you can take it from here.

**Comment by byashimov** [comment]
Hey @mortenlj 
commit linter does not pass, I guess squashing into one commit will solve this.

**Review by byashimov — APPROVED** [review]

**Pull request merged**
