### PR TITLE
fix(docs): indentation formatting on several admonitions

### PR DESCRIPTION
**Pull request by vidofnir**
There was missing indentation on several admonitions which resulted in a admonition box (e.g. 'Note') and the text that should be inside the box was just appearing below the box as regular text.

Fix:
After a '!!! note' etc. the admonition content on the next line need to be aligned with the 'note'.

### CODE REVIEW

**Comment by byashimov** [comment]
Hey @vidofnir! Indeed, the admonitions formatting is invalid.
Could you amend the commit title to "fix(docs): indentation formatting on several admonitions" please? We use [conventionalcommits](conventionalcommitshttps://www.conventionalcommits.org/en/v1.0.0/) and the linter doesn't let me merge your PR. Thank you for your contribution!

**Comment by vidofnir** [comment]
I did the following on my side now:
```
git commit --amend -m "fix(docs): indentation formatting on several admonitions"
git push origin main --force
```

**Comment by Serpentiel** [comment]
Hey, @vidofnir! 👋

I'll run the CI now, let's see if there's anything to be adjusted :)

**Review by Serpentiel — APPROVED** [review]
lgtm

**Pull request merged**
