### PR TITLE
fix(controllers): object not committed properly

### PR DESCRIPTION
**Pull request by byashimov**
This PR:
- fixes object updates lose during reconciliation
- sets error conditions on basic controller level

### CODE REVIEW

**Comment by tkaesserfm** [comment]
@byashimov yes, you were right! :laughing:

**Comment by byashimov** [comment]
> @byashimov yes, you were right! 😆

Hey. What do you mean? :)

**Comment by tkaesserfm** [comment]
@byashimov yes, but i only see the issue for KafkaACL. 
We're only using kafka-related stuff though. What works is ServiceUser and KafkaTopic.

**Comment by tkaesserfm** [comment]
Ah i see, i was talking "Status Conditions" so different thing but the symptom seems the same.

**Review by ivan-savciuc — APPROVED** [review]
LGTM

**Pull request merged**
