### PR TITLE
upgrade Kafka kind

### PR DESCRIPTION
**Pull request by byashimov**
- Updates Kafka's user config
- Uses generic service controller
- Uses floats instead of ints for `number`
- Fixes big int overflow
- Fixes sheriff marshal service types without user config

### CODE REVIEW

**Comment by byashimov** [comment]
Tests https://github.com/aiven/aiven-operator/actions/runs/4043256283

**Comment by byashimov** [comment]
New pushes are rebase on master.

**Review by ivan-savciuc — COMMENTED** [review]
Something is wrong with the topic name regexp? 
```
go generate ./...
2023/02/01 19:19:31 field "group_concat_max_len" has minimum >= maximum: 4 >= -9223372036854775808
2023/02/01 19:19:31 field "max_failover_replication_time_lag" has minimum >= maximum: 10 >= -9223372036854775808
2023/02/01 19:19:31 field "log_cleaner_max_compaction_lag_ms" has minimum >= maximum: 30000 >= -9223372036854775808
2023/02/01 19:19:31 field "log_cleaner_min_compaction_lag_ms" has minimum >= maximum: 0 >= -9223372036854775808
2023/02/01 19:19:31 field "log_flush_interval_messages" has minimum >= maximum: 1 >= -9223372036854775808
2023/02/01 19:19:31 field "log_flush_interval_ms" has minimum >= maximum: 0 >= -9223372036854775808
2023/02/01 19:19:31 field "log_message_timestamp_difference_max_ms" has minimum >= maximum: 0 >= -9223372036854775808
2023/02/01 19:19:31 field "log_retention_bytes" has minimum >= maximum: -1 >= -9223372036854775808
2023/02/01 19:19:31 field "log_retention_ms" has minimum >= maximum: -1 >= -9223372036854775808
2023/02/01 19:19:31 field "log_roll_jitter_ms" has minimum >= maximum: 0 >= -9223372036854775808
2023/02/01 19:19:31 field "log_roll_ms" has minimum >= maximum: 1 >= -9223372036854775808
2023/02/01 19:19:31 can't compile field "topic_name" regex `^(?!\.$|\.\.$)[-_.A-Za-z0-9]+$`: error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

**Review by ivan-savciuc — CHANGES_REQUESTED** [review]
Some more testing outcomes: 
- `make install` is not rely changing anything, for example of a user already running current Aiven operator and would upgrade to this one I would expect to see some changes in the CRD definitions but there are none
```
customresourcedefinition.apiextensions.k8s.io/cassandras.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/clickhouses.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/clickhouseusers.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/connectionpools.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/databases.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/grafanas.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/kafkaacls.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/kafkaconnectors.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/kafkaconnects.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/kafkas.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/kafkaschemas.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/kafkatopics.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/mysqls.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/opensearches.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/postgresqls.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/projects.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/projectvpcs.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/redis.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/serviceintegrations.aiven.io unchanged
customresourcedefinition.apiextensions.k8s.io/serviceusers.aiven.io unchange
```
- after upgrading a working cluster with a Kafka service that has `ip_filters:[""...]` to this version triggers these errors: 
```
W0201 21:17:53.596426 1387242 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: failed to list *v1alpha1.Kafka: json: cannot unmarshal string into Go struct field KafkaUserConfig.items.spec.userConfig.ip_filter of type kafkauserconfig.IpFilter
E0201 21:17:53.596874 1387242 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Kafka: failed to list *v1alpha1.Kafka: json: cannot unmarshal string into Go struct field KafkaUserConfig.items.spec.userConfig.ip_filter of type kafkauserconfig.IpFilter
``` 
Changing the `ip_filters` type from string to objects is a breaking change, and I think it is best to support `[]string` type until GA.

**Comment by byashimov** [comment]
> Something is wrong, try go generate

Warning only, nothing special. But made it fail before this warnings for amd64. On arm they won't even happen.

> make install is not rely changing anything

This is weird. If so you shouldn't have had run into ip_filters issue.

> Changing the ip_filters type from string to objects is a breaking change, and I think it is best to support []string type until GA.

I would say it's better make breaking changes before we v1.0

> after upgrading a working cluster with a Kafka service that has ip_filters:[""...] to this version triggers these errors:

Thanks. Added custom unmarshal.

**Review by ivan-savciuc — APPROVED** [review]
LGTM, tested again and all works great!

**Pull request merged**
